/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AInput: typeof import('ant-design-vue/es')['Input']
    BetterScroll: typeof import('./src/components/common/better-scroll.vue')['default']
    Collapse: typeof import('./src/components/Collapse.vue')['default']
    CollapseItem: typeof import('./src/components/CollapsePanel/CollapseItem.vue')['default']
    CollapsePanel: typeof import('./src/components/CollapsePanel/index.vue')['default']
    CollapseTransiation: typeof import('./src/components/CollapsePanel/CollapseTransiation.vue')['default']
    CollapseTransition: typeof import('./src/components/CollapsePanel/CollapseTransition.vue')['default']
    CollapseTranslation: typeof import('./src/components/CollapsePanel/CollapseTranslation.vue')['default']
    Examle: typeof import('./src/components/examle.vue')['default']
    HeightProgress: typeof import('./src/components/common/height-progress.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tags: typeof import('./src/components/Tags.vue')['default']
  }
}
